name: kothon
description: Anonymous Messaging App like NGL or Chiti.me
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  provider: ^6.1.1
  share_plus: ^11.0.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.2.5
  fluttertoast: ^8.2.2
  intl: ^0.20.2
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  flutter_sound: ^9.2.13+1
  permission_handler: ^12.0.1
  firebase_storage: 12.4.9
  path_provider: ^2.1.3
  firebase_dynamic_links: ^6.1.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  
    

  fonts:
    - family: SiyamRupali
      fonts:
        - asset: assets/fonts/SiyamRupali.ttf
  assets:
    - assets/fonts/
    - assets/images/kothon.png
    - assets/images/notepad_texture.png